global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
# Enable API and Dashboard  (remove them in production)
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  cloudflare:
    acme:
      email: "{ACME_EMAIL}" # replace with your email
      storage: "/var/traefik/certs/cloudflare-acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: "EC256"
      dnsChallenge:
        provider: "cloudflare"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false